### ISSUE TITLE
Problem with the provided image format?

### ISSUE THREAD

**Issue by abrenoch** [packruler/BacklightHandler#1]
Hey @packruler, I'm trying out some chunks of your code in the grabber I'm working on, and I'm running into an issues I think with the defined ImageReader format:

The image reader is initialized with RGB_565 here:
https://github.com/packruler/BacklightHandler/blob/3c1914c1cc82c5fc112fe8b86619f591dc72f3c7/mobile/src/main/java/com/packruler/backlighthandler/ScreenHandler.java#L151

But using that format throws out an error (I can't remember what it was at the moment).. I found using PixelFormat.RGBA_8888 instead allows it to work, but obviously the code to change that image data into the RGB values hyperion needs to be revised as well.

Looking at the `for` loop in your processor:
https://github.com/packruler/BacklightHandler/blob/3c1914c1cc82c5fc112fe8b86619f591dc72f3c7/mobile/src/main/java/com/packruler/backlighthandler/Processing/ImageProcessing.java#L49

I'm honestly not sure how exactly the values being used there actually work (admittedly I'm not that familiar with bit manipulation), even starting with the "Reconstruct 16 bit rgb565 value from two bytes" line! Why is that rgb data spread over 2 bytes rather than 1 or 3? Maybe I just need something to reference to get a better idea of what is going on, if you could point me towards something I would really appreciate it!

Thanks!

**Comment by packruler** [comment]
Honestly I haven't touched this in a while and can't be sure my memory is accurate... But IIRC I did the bit conversion to take the RGB565 -> RGB888 because I couldn't access a RGB888 and RGBA8888 because of support issues.... These issues may have been fixed... but I am not positive.
Sorry I can't really remember much more.
Let me know as you run into questions and something may jog my memory.

**Comment by abrenoch** [comment]
So I got some time to dig further into this, and it was actually a lot easier than I was making it out to be - you can basically feed the byte array each value from the RGBA_8888 buffer directly, while omitting the alpha channel. Guess I was just over-thinking it!

Thanks for the the help!
